#!/bin/bash

pid=$$
palette="/tmp/gif-palette-$pid.png"

filters="fps=15"

ffmpeg -v warning -i $1 -vf "$filters,palettegen" -y $palette
ffmpeg -v warning -i $1 -i $palette -lavfi "$filters [x]; [x][1:v] paletteuse" -y $2
